# Generated by Django 4.2.3 on 2023-08-03 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('it_pojmy', '0002_kategorie_clanek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('nazev', models.CharField(max_length=100)),
                ('popis', models.CharField(blank=True, max_length=500)),
                ('datum', models.DateTimeField(blank=True, null=True)),
                ('kategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='it_pojmy.kategorie')),
            ],
        ),
    ]
